name: Build and Release Executable

on:
  push:
    branches: [ main ]

permissions:
  contents: write  

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pip install opencv-python rawpy numpy pillow
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --hidden-import tkinter --hidden-import cv2 --hidden-import numpy --hidden-import rawpy --hidden-import PIL --hidden-import PIL.Image --hidden-import PIL.ImageFont --hidden-import PIL.ImageDraw --hidden-import PIL._tkinter --collect-submodules photodisarm .\src\launcher.py
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release-${{ github.run_number }}
        name: Release ${{ github.run_number }}
        files: ./dist/launcher.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}